version: '3.4'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./src:/app/src:delegated
    ports: 
      - "${PORT}:3000"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sims_todo
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql